const CLOUD_STORAGE_IMAGES_BUCKET = 'img.chrisvogt.me'

const CLOUD_STORAGE_INSTAGRAM_PATH = 'ig/'

const DATABASE_COLLECTION_SPOTIFY = 'spotify'

const DATABASE_COLLECTION_INSTAGRAM = 'instagram'

const IMAGE_CDN_BASE_URL = 'https://img.chrisvogt.me/'

module.exports = {
  CLOUD_STORAGE_IMAGES_BUCKET,
  CLOUD_STORAGE_INSTAGRAM_PATH,
  DATABASE_COLLECTION_INSTAGRAM,
  DATABASE_COLLECTION_SPOTIFY,
  IMAGE_CDN_BASE_URL
}
